/*
 * Swagger Appointment managment - RTM - OpenAPI 3.1
 *
 * This is the OpenAPI 3.1 specification of Appointment managment - RTM.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: mehmet-ali.asar@protonmail.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using AppointmentManagement.API.Attributes;
using AppointmentManagement.API.Models;
using Microsoft.AspNetCore.DataProtection.KeyManagement;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;
using System.Linq;

namespace AppointmentManagement.API.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class CONTACTApiController : ControllerBase
    {

        private readonly AppDbContext _context;

        /// <summary>
        /// Initializes a new instance of the <see cref="CONTACTApiController"/> class.
        /// </summary>
        /// <param name="context">The database context for appointments.</param>
        public CONTACTApiController(AppDbContext context)
        {
            _context = context;
        }

        private bool ItemExists(long id)
        {
            return _context.Contact.Any(CONTACT => CONTACT.ContactID == id);
        }

        /// <summary>
        /// Create a new contact
        /// </summary>
        /// <remarks>Create a new contact by Id</remarks>
        /// <param name="CONTACT"></param>
        /// <response code="200"></response>
        /// <response code="0"></response>
        [HttpPost]
        [Route("/api/v3/contacts")]
        //[Authorize(Policy = "api_key")]
        [Consumes("application/json")]
        [ValidateModelState]
        [SwaggerOperation("CreateContact")]
        public virtual async Task<IActionResult> CreateContactAsync([FromBody]CONTACT CONTACT)
        {

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);
            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0);


            if (CONTACT == null)
            {
                return BadRequest();
            }

            _context.Contact.Add(CONTACT);
            await _context.SaveChangesAsync();


            string apiKey = HttpContext.RequestServices.GetService<IConfiguration>().GetValue<string>("X-API-Key");

            if (HttpContext.Request.Headers["X-API-Key"] == apiKey)
                return CreatedAtAction(nameof(GetContacts), new { id = CONTACT.ContactID }, CONTACT);
            else return Unauthorized();

            // throw new NotImplementedException();
        }

        /// <summary>
        /// Delete a single contact
        /// </summary>
        /// <remarks>Delete a single contact by Id</remarks>
        /// <param name="contactID"></param>
        /// <response code="204">Deleted the contact</response>
        /// <response code="0"></response>
        [HttpDelete]
        [Route("/api/v3/contacts/{ContactID}")]
        //[Authorize(Policy = "api_key")]
        [ValidateModelState]
        [SwaggerOperation("DeleteContact")]
        public async virtual Task<IActionResult> DeleteContact([FromRoute (Name = "ContactID")][Required]long contactID)
        {

            string apiKey = HttpContext.RequestServices.GetService<IConfiguration>().GetValue<string>("X-API-Key");
            var item = await _context.Contact.FindAsync(contactID);

            if (item == null)
            {
                return NotFound();
            }

            _context.Contact.Remove(item);
            await _context.SaveChangesAsync();

            if (HttpContext.Request.Headers["X-API-Key"] == apiKey) return NoContent();
            else return Unauthorized();

        }

        /// <summary>
        /// Get a single contact
        /// </summary>
        /// <remarks>Get a single contact by Id</remarks>
        /// <param name="contactID"></param>
        /// <response code="200"></response>
        /// <response code="0"></response>
        [HttpGet]
        [Route("/api/v3/contacts/{ContactID}")]
        [ValidateModelState]
        [SwaggerOperation("GetContact")]
        public virtual async Task<IActionResult> GetContactAsync([FromRoute (Name = "ContactID")][Required]long contactID)
        {


            var contact = await _context.Contact.FindAsync(contactID);// ToListAsync(); <- for multiple

            string apiKey = HttpContext.RequestServices.GetService<IConfiguration>().GetValue<string>("X-API-Key");

            if (HttpContext.Request.Headers["X-API-Key"] == apiKey) return Ok(contact);
            else return Unauthorized();

            }


        /// <summary>
        /// Get all contacts
        /// </summary>
        /// <remarks>Get all contacts as JSON</remarks>
        /// <response code="200">Success</response>
        /// <response code="0"></response>
        [HttpGet]
        [Route("/api/v3/contacts")]
        //[Authorize(Policy = "api_key")]
        [ValidateModelState]
        [SwaggerOperation("GetContacts")]
        [SwaggerResponse(statusCode: 200, type: typeof(Object), description: "Success")]
        public virtual async Task<IActionResult> GetContacts()
        {
                     
            string apiKey = HttpContext.RequestServices.GetService<IConfiguration>().GetValue<string>("X-API-Key");
            if (HttpContext.Request.Headers["X-API-Key"] == apiKey) return new ObjectResult(await _context.Contact.ToListAsync());
            else return Unauthorized();
        }

        /// <summary>
        /// Replace a single contact
        /// </summary>
        /// <remarks>Replace a single contact by Id</remarks>
        /// <param name="contactID"></param>
        /// <param name="CONTACT"></param>
        /// <response code="200"></response>
        /// <response code="0"></response>
        [HttpPut]
        [Route("/api/v3/contacts/{ContactID}")]
        //[Authorize(Policy = "api_key")]
        [Consumes("application/json")]
        [ValidateModelState]
        [SwaggerOperation("ReplaceContact")]
        public virtual async Task<IActionResult> ReplaceContact([FromRoute (Name = "ContactID")][Required]long contactID, [FromBody]CONTACT CONTACT)
        {
            string apiKey = HttpContext.RequestServices.GetService<IConfiguration>().GetValue<string>("X-API-Key");

            var contact = await _context.Contact.FindAsync(contactID);

            if (contactID != CONTACT.ContactID)
            {
                return BadRequest();
            }




            var existingEntity = _context.Contact.FirstOrDefault(c => c.ContactID == CONTACT.ContactID);
            if (existingEntity != null)
            {
                _context.Entry(existingEntity).CurrentValues.SetValues(CONTACT);
            }
            else
            {
                _context.Attach(CONTACT);
                _context.Entry(CONTACT).State = EntityState.Modified;
            }

            try
            {
                await _context.SaveChangesAsync();
                if (HttpContext.Request.Headers["X-API-Key"] == apiKey)
                    return Ok("Contact has been replaced");
                else return Unauthorized();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ItemExists(contactID))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

        }
    }
}
