/*
 * Swagger Appointment managment - RTM - OpenAPI 3.1
 *
 * This is the OpenAPI 3.0 specification of Appointment managment - RTM.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: mehmet-ali.asar@protonmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AppointmentManagement.Client.Model;
using AppointmentManagement.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AppointmentManagement.Client.Test.Model
{
    /// <summary>
    ///  Class for testing APPOINTMENT
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class APPOINTMENTTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for APPOINTMENT
        //private APPOINTMENT instance;

        public APPOINTMENTTests()
        {
            // TODO uncomment below to create an instance of APPOINTMENT
            //instance = new APPOINTMENT();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of APPOINTMENT
        /// </summary>
        [Fact]
        public void APPOINTMENTInstanceTest()
        {
            // TODO uncomment below to test "IsType" APPOINTMENT
            //Assert.IsType<APPOINTMENT>(instance);
        }

        /// <summary>
        /// Test the property 'AppointmentID'
        /// </summary>
        [Fact]
        public void AppointmentIDTest()
        {
            // TODO unit test for the property 'AppointmentID'
        }

        /// <summary>
        /// Test the property 'ContactID'
        /// </summary>
        [Fact]
        public void ContactIDTest()
        {
            // TODO unit test for the property 'ContactID'
        }

        /// <summary>
        /// Test the property 'Repetition'
        /// </summary>
        [Fact]
        public void RepetitionTest()
        {
            // TODO unit test for the property 'Repetition'
        }

        /// <summary>
        /// Test the property 'Topic'
        /// </summary>
        [Fact]
        public void TopicTest()
        {
            // TODO unit test for the property 'Topic'
        }

        /// <summary>
        /// Test the property 'Note'
        /// </summary>
        [Fact]
        public void NoteTest()
        {
            // TODO unit test for the property 'Note'
        }

        /// <summary>
        /// Test the property 'StartTime'
        /// </summary>
        [Fact]
        public void StartTimeTest()
        {
            // TODO unit test for the property 'StartTime'
        }

        /// <summary>
        /// Test the property 'EndTime'
        /// </summary>
        [Fact]
        public void EndTimeTest()
        {
            // TODO unit test for the property 'EndTime'
        }

        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Fact]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }
    }
}
