/*
 * Swagger Appointment managment - RTM - OpenAPI 3.1
 *
 * This is the OpenAPI 3.0 specification of Appointment managment - RTM.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: mehmet-ali.asar@protonmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AppointmentManagement.Client.Model;
using AppointmentManagement.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AppointmentManagement.Client.Test.Model
{
    /// <summary>
    ///  Class for testing CONTACT
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CONTACTTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CONTACT
        //private CONTACT instance;

        public CONTACTTests()
        {
            // TODO uncomment below to create an instance of CONTACT
            //instance = new CONTACT();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CONTACT
        /// </summary>
        [Fact]
        public void CONTACTInstanceTest()
        {
            // TODO uncomment below to test "IsType" CONTACT
            //Assert.IsType<CONTACT>(instance);
        }

        /// <summary>
        /// Test the property 'ContactID'
        /// </summary>
        [Fact]
        public void ContactIDTest()
        {
            // TODO unit test for the property 'ContactID'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'PostalCode'
        /// </summary>
        [Fact]
        public void PostalCodeTest()
        {
            // TODO unit test for the property 'PostalCode'
        }

        /// <summary>
        /// Test the property 'Street'
        /// </summary>
        [Fact]
        public void StreetTest()
        {
            // TODO unit test for the property 'Street'
        }

        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Fact]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }

        /// <summary>
        /// Test the property 'Note'
        /// </summary>
        [Fact]
        public void NoteTest()
        {
            // TODO unit test for the property 'Note'
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        /// Test the property 'ContactType'
        /// </summary>
        [Fact]
        public void ContactTypeTest()
        {
            // TODO unit test for the property 'ContactType'
        }

        /// <summary>
        /// Test the property 'Telephone'
        /// </summary>
        [Fact]
        public void TelephoneTest()
        {
            // TODO unit test for the property 'Telephone'
        }

        /// <summary>
        /// Test the property 'Company'
        /// </summary>
        [Fact]
        public void CompanyTest()
        {
            // TODO unit test for the property 'Company'
        }
    }
}
