/*
 * Swagger Appointment managment - RTM - OpenAPI 3.1
 *
 * This is the OpenAPI 3.0 specification of Appointment managment - RTM.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: mehmet-ali.asar@protonmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AppointmentManagement.Client.Model;
using AppointmentManagement.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AppointmentManagement.Client.Test.Model
{
    /// <summary>
    ///  Class for testing REMINDER
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class REMINDERTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for REMINDER
        //private REMINDER instance;

        public REMINDERTests()
        {
            // TODO uncomment below to create an instance of REMINDER
            //instance = new REMINDER();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of REMINDER
        /// </summary>
        [Fact]
        public void REMINDERInstanceTest()
        {
            // TODO uncomment below to test "IsType" REMINDER
            //Assert.IsType<REMINDER>(instance);
        }

        /// <summary>
        /// Test the property 'ReminderID'
        /// </summary>
        [Fact]
        public void ReminderIDTest()
        {
            // TODO unit test for the property 'ReminderID'
        }

        /// <summary>
        /// Test the property 'AppointmentID'
        /// </summary>
        [Fact]
        public void AppointmentIDTest()
        {
            // TODO unit test for the property 'AppointmentID'
        }

        /// <summary>
        /// Test the property 'Time'
        /// </summary>
        [Fact]
        public void TimeTest()
        {
            // TODO unit test for the property 'Time'
        }
    }
}
