/*
 * Swagger Appointment managment - RTM - OpenAPI 3.1
 *
 * This is the OpenAPI 3.0 specification of Appointment managment - RTM.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: mehmet-ali.asar@protonmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using AppointmentManagement.Client.Client;
using AppointmentManagement.Client.Client.Auth;
using AppointmentManagement.Client.Model;

namespace AppointmentManagement.Client.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAPPOINTMENTApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Create a new appointment
        /// </summary>
        /// <remarks>
        /// Create a new appointment by Id
        /// </remarks>
        /// <exception cref="AppointmentManagement.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="APPOINTMENT"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        void CreateAppointment(APPOINTMENT APPOINTMENT, int operationIndex = 0);

        /// <summary>
        /// Create a new appointment
        /// </summary>
        /// <remarks>
        /// Create a new appointment by Id
        /// </remarks>
        /// <exception cref="AppointmentManagement.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="APPOINTMENT"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> CreateAppointmentWithHttpInfo(APPOINTMENT APPOINTMENT, int operationIndex = 0);
        /// <summary>
        /// Delete a single appointment
        /// </summary>
        /// <remarks>
        /// Delete a single appointment by Id
        /// </remarks>
        /// <exception cref="AppointmentManagement.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appointmentID"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        void DeleteAppointment(Object appointmentID, int operationIndex = 0);

        /// <summary>
        /// Delete a single appointment
        /// </summary>
        /// <remarks>
        /// Delete a single appointment by Id
        /// </remarks>
        /// <exception cref="AppointmentManagement.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appointmentID"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> DeleteAppointmentWithHttpInfo(Object appointmentID, int operationIndex = 0);
        /// <summary>
        /// Get a single appointment
        /// </summary>
        /// <remarks>
        /// Get a single appointment by Id
        /// </remarks>
        /// <exception cref="AppointmentManagement.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appointmentID"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        void GetAppointment(Object appointmentID, int operationIndex = 0);

        /// <summary>
        /// Get a single appointment
        /// </summary>
        /// <remarks>
        /// Get a single appointment by Id
        /// </remarks>
        /// <exception cref="AppointmentManagement.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appointmentID"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> GetAppointmentWithHttpInfo(Object appointmentID, int operationIndex = 0);
        /// <summary>
        /// Get all appointments
        /// </summary>
        /// <remarks>
        /// Get all appointments as JSON
        /// </remarks>
        /// <exception cref="AppointmentManagement.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Object</returns>
        Object GetAppointments(int operationIndex = 0);

        /// <summary>
        /// Get all appointments
        /// </summary>
        /// <remarks>
        /// Get all appointments as JSON
        /// </remarks>
        /// <exception cref="AppointmentManagement.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Object> GetAppointmentsWithHttpInfo(int operationIndex = 0);
        /// <summary>
        /// Replace a single appointment
        /// </summary>
        /// <remarks>
        /// Replace a single appointment by Id
        /// </remarks>
        /// <exception cref="AppointmentManagement.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appointmentID"></param>
        /// <param name="APPOINTMENT"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        void ReplaceAppointment(Object appointmentID, APPOINTMENT APPOINTMENT, int operationIndex = 0);

        /// <summary>
        /// Replace a single appointment
        /// </summary>
        /// <remarks>
        /// Replace a single appointment by Id
        /// </remarks>
        /// <exception cref="AppointmentManagement.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appointmentID"></param>
        /// <param name="APPOINTMENT"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> ReplaceAppointmentWithHttpInfo(Object appointmentID, APPOINTMENT APPOINTMENT, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAPPOINTMENTApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Create a new appointment
        /// </summary>
        /// <remarks>
        /// Create a new appointment by Id
        /// </remarks>
        /// <exception cref="AppointmentManagement.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="APPOINTMENT"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task CreateAppointmentAsync(APPOINTMENT APPOINTMENT, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Create a new appointment
        /// </summary>
        /// <remarks>
        /// Create a new appointment by Id
        /// </remarks>
        /// <exception cref="AppointmentManagement.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="APPOINTMENT"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> CreateAppointmentWithHttpInfoAsync(APPOINTMENT APPOINTMENT, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Delete a single appointment
        /// </summary>
        /// <remarks>
        /// Delete a single appointment by Id
        /// </remarks>
        /// <exception cref="AppointmentManagement.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appointmentID"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task DeleteAppointmentAsync(Object appointmentID, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Delete a single appointment
        /// </summary>
        /// <remarks>
        /// Delete a single appointment by Id
        /// </remarks>
        /// <exception cref="AppointmentManagement.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appointmentID"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> DeleteAppointmentWithHttpInfoAsync(Object appointmentID, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Get a single appointment
        /// </summary>
        /// <remarks>
        /// Get a single appointment by Id
        /// </remarks>
        /// <exception cref="AppointmentManagement.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appointmentID"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task GetAppointmentAsync(Object appointmentID, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get a single appointment
        /// </summary>
        /// <remarks>
        /// Get a single appointment by Id
        /// </remarks>
        /// <exception cref="AppointmentManagement.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appointmentID"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> GetAppointmentWithHttpInfoAsync(Object appointmentID, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Get all appointments
        /// </summary>
        /// <remarks>
        /// Get all appointments as JSON
        /// </remarks>
        /// <exception cref="AppointmentManagement.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> GetAppointmentsAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get all appointments
        /// </summary>
        /// <remarks>
        /// Get all appointments as JSON
        /// </remarks>
        /// <exception cref="AppointmentManagement.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> GetAppointmentsWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Replace a single appointment
        /// </summary>
        /// <remarks>
        /// Replace a single appointment by Id
        /// </remarks>
        /// <exception cref="AppointmentManagement.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appointmentID"></param>
        /// <param name="APPOINTMENT"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task ReplaceAppointmentAsync(Object appointmentID, APPOINTMENT APPOINTMENT, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Replace a single appointment
        /// </summary>
        /// <remarks>
        /// Replace a single appointment by Id
        /// </remarks>
        /// <exception cref="AppointmentManagement.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appointmentID"></param>
        /// <param name="APPOINTMENT"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ReplaceAppointmentWithHttpInfoAsync(Object appointmentID, APPOINTMENT APPOINTMENT, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAPPOINTMENTApi : IAPPOINTMENTApiSync, IAPPOINTMENTApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class APPOINTMENTApi : IAPPOINTMENTApi
    {
        private AppointmentManagement.Client.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="APPOINTMENTApi"/> class.
        /// </summary>
        /// <returns></returns>
        public APPOINTMENTApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="APPOINTMENTApi"/> class.
        /// </summary>
        /// <returns></returns>
        public APPOINTMENTApi(string basePath)
        {
            this.Configuration = AppointmentManagement.Client.Client.Configuration.MergeConfigurations(
                AppointmentManagement.Client.Client.GlobalConfiguration.Instance,
                new AppointmentManagement.Client.Client.Configuration { BasePath = basePath }
            );
            this.Client = new AppointmentManagement.Client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new AppointmentManagement.Client.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = AppointmentManagement.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="APPOINTMENTApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public APPOINTMENTApi(AppointmentManagement.Client.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = AppointmentManagement.Client.Client.Configuration.MergeConfigurations(
                AppointmentManagement.Client.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new AppointmentManagement.Client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new AppointmentManagement.Client.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = AppointmentManagement.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="APPOINTMENTApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public APPOINTMENTApi(AppointmentManagement.Client.Client.ISynchronousClient client, AppointmentManagement.Client.Client.IAsynchronousClient asyncClient, AppointmentManagement.Client.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = AppointmentManagement.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public AppointmentManagement.Client.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public AppointmentManagement.Client.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public AppointmentManagement.Client.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public AppointmentManagement.Client.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Create a new appointment Create a new appointment by Id
        /// </summary>
        /// <exception cref="AppointmentManagement.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="APPOINTMENT"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        public void CreateAppointment(APPOINTMENT APPOINTMENT, int operationIndex = 0)
        {
            CreateAppointmentWithHttpInfo(APPOINTMENT);
        }

        /// <summary>
        /// Create a new appointment Create a new appointment by Id
        /// </summary>
        /// <exception cref="AppointmentManagement.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="APPOINTMENT"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public AppointmentManagement.Client.Client.ApiResponse<Object> CreateAppointmentWithHttpInfo(APPOINTMENT APPOINTMENT, int operationIndex = 0)
        {
            // verify the required parameter 'APPOINTMENT' is set
            if (APPOINTMENT == null)
            {
                throw new AppointmentManagement.Client.Client.ApiException(400, "Missing required parameter 'APPOINTMENT' when calling APPOINTMENTApi->CreateAppointment");
            }

            AppointmentManagement.Client.Client.RequestOptions localVarRequestOptions = new AppointmentManagement.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = AppointmentManagement.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = AppointmentManagement.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = APPOINTMENT;

            localVarRequestOptions.Operation = "APPOINTMENTApi.CreateAppointment";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (appointmentmanagement_auth) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<Object>("/appointments", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateAppointment", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create a new appointment Create a new appointment by Id
        /// </summary>
        /// <exception cref="AppointmentManagement.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="APPOINTMENT"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task CreateAppointmentAsync(APPOINTMENT APPOINTMENT, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            await CreateAppointmentWithHttpInfoAsync(APPOINTMENT, operationIndex, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Create a new appointment Create a new appointment by Id
        /// </summary>
        /// <exception cref="AppointmentManagement.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="APPOINTMENT"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<AppointmentManagement.Client.Client.ApiResponse<Object>> CreateAppointmentWithHttpInfoAsync(APPOINTMENT APPOINTMENT, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'APPOINTMENT' is set
            if (APPOINTMENT == null)
            {
                throw new AppointmentManagement.Client.Client.ApiException(400, "Missing required parameter 'APPOINTMENT' when calling APPOINTMENTApi->CreateAppointment");
            }


            AppointmentManagement.Client.Client.RequestOptions localVarRequestOptions = new AppointmentManagement.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = AppointmentManagement.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = AppointmentManagement.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = APPOINTMENT;

            localVarRequestOptions.Operation = "APPOINTMENTApi.CreateAppointment";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (appointmentmanagement_auth) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<Object>("/appointments", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateAppointment", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete a single appointment Delete a single appointment by Id
        /// </summary>
        /// <exception cref="AppointmentManagement.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appointmentID"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        public void DeleteAppointment(Object appointmentID, int operationIndex = 0)
        {
            DeleteAppointmentWithHttpInfo(appointmentID);
        }

        /// <summary>
        /// Delete a single appointment Delete a single appointment by Id
        /// </summary>
        /// <exception cref="AppointmentManagement.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appointmentID"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public AppointmentManagement.Client.Client.ApiResponse<Object> DeleteAppointmentWithHttpInfo(Object appointmentID, int operationIndex = 0)
        {
            // verify the required parameter 'appointmentID' is set
            if (appointmentID == null)
            {
                throw new AppointmentManagement.Client.Client.ApiException(400, "Missing required parameter 'appointmentID' when calling APPOINTMENTApi->DeleteAppointment");
            }

            AppointmentManagement.Client.Client.RequestOptions localVarRequestOptions = new AppointmentManagement.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = AppointmentManagement.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = AppointmentManagement.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("AppointmentID", AppointmentManagement.Client.Client.ClientUtils.ParameterToString(appointmentID)); // path parameter

            localVarRequestOptions.Operation = "APPOINTMENTApi.DeleteAppointment";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (appointmentmanagement_auth) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<Object>("/appointments/{AppointmentID}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteAppointment", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete a single appointment Delete a single appointment by Id
        /// </summary>
        /// <exception cref="AppointmentManagement.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appointmentID"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task DeleteAppointmentAsync(Object appointmentID, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            await DeleteAppointmentWithHttpInfoAsync(appointmentID, operationIndex, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Delete a single appointment Delete a single appointment by Id
        /// </summary>
        /// <exception cref="AppointmentManagement.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appointmentID"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<AppointmentManagement.Client.Client.ApiResponse<Object>> DeleteAppointmentWithHttpInfoAsync(Object appointmentID, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'appointmentID' is set
            if (appointmentID == null)
            {
                throw new AppointmentManagement.Client.Client.ApiException(400, "Missing required parameter 'appointmentID' when calling APPOINTMENTApi->DeleteAppointment");
            }


            AppointmentManagement.Client.Client.RequestOptions localVarRequestOptions = new AppointmentManagement.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = AppointmentManagement.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = AppointmentManagement.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("AppointmentID", AppointmentManagement.Client.Client.ClientUtils.ParameterToString(appointmentID)); // path parameter

            localVarRequestOptions.Operation = "APPOINTMENTApi.DeleteAppointment";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (appointmentmanagement_auth) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.DeleteAsync<Object>("/appointments/{AppointmentID}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteAppointment", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get a single appointment Get a single appointment by Id
        /// </summary>
        /// <exception cref="AppointmentManagement.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appointmentID"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        public void GetAppointment(Object appointmentID, int operationIndex = 0)
        {
            GetAppointmentWithHttpInfo(appointmentID);
        }

        /// <summary>
        /// Get a single appointment Get a single appointment by Id
        /// </summary>
        /// <exception cref="AppointmentManagement.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appointmentID"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public AppointmentManagement.Client.Client.ApiResponse<Object> GetAppointmentWithHttpInfo(Object appointmentID, int operationIndex = 0)
        {
            // verify the required parameter 'appointmentID' is set
            if (appointmentID == null)
            {
                throw new AppointmentManagement.Client.Client.ApiException(400, "Missing required parameter 'appointmentID' when calling APPOINTMENTApi->GetAppointment");
            }

            AppointmentManagement.Client.Client.RequestOptions localVarRequestOptions = new AppointmentManagement.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = AppointmentManagement.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = AppointmentManagement.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("AppointmentID", AppointmentManagement.Client.Client.ClientUtils.ParameterToString(appointmentID)); // path parameter

            localVarRequestOptions.Operation = "APPOINTMENTApi.GetAppointment";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (appointmentmanagement_auth) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<Object>("/appointments/{AppointmentID}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetAppointment", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get a single appointment Get a single appointment by Id
        /// </summary>
        /// <exception cref="AppointmentManagement.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appointmentID"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task GetAppointmentAsync(Object appointmentID, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            await GetAppointmentWithHttpInfoAsync(appointmentID, operationIndex, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Get a single appointment Get a single appointment by Id
        /// </summary>
        /// <exception cref="AppointmentManagement.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appointmentID"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<AppointmentManagement.Client.Client.ApiResponse<Object>> GetAppointmentWithHttpInfoAsync(Object appointmentID, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'appointmentID' is set
            if (appointmentID == null)
            {
                throw new AppointmentManagement.Client.Client.ApiException(400, "Missing required parameter 'appointmentID' when calling APPOINTMENTApi->GetAppointment");
            }


            AppointmentManagement.Client.Client.RequestOptions localVarRequestOptions = new AppointmentManagement.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = AppointmentManagement.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = AppointmentManagement.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("AppointmentID", AppointmentManagement.Client.Client.ClientUtils.ParameterToString(appointmentID)); // path parameter

            localVarRequestOptions.Operation = "APPOINTMENTApi.GetAppointment";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (appointmentmanagement_auth) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<Object>("/appointments/{AppointmentID}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetAppointment", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get all appointments Get all appointments as JSON
        /// </summary>
        /// <exception cref="AppointmentManagement.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Object</returns>
        public Object GetAppointments(int operationIndex = 0)
        {
            AppointmentManagement.Client.Client.ApiResponse<Object> localVarResponse = GetAppointmentsWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get all appointments Get all appointments as JSON
        /// </summary>
        /// <exception cref="AppointmentManagement.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object</returns>
        public AppointmentManagement.Client.Client.ApiResponse<Object> GetAppointmentsWithHttpInfo(int operationIndex = 0)
        {
            AppointmentManagement.Client.Client.RequestOptions localVarRequestOptions = new AppointmentManagement.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/xml"
            };

            var localVarContentType = AppointmentManagement.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = AppointmentManagement.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "APPOINTMENTApi.GetAppointments";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (appointmentmanagement_auth) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<Object>("/appointments", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetAppointments", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get all appointments Get all appointments as JSON
        /// </summary>
        /// <exception cref="AppointmentManagement.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Object> GetAppointmentsAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            AppointmentManagement.Client.Client.ApiResponse<Object> localVarResponse = await GetAppointmentsWithHttpInfoAsync(operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get all appointments Get all appointments as JSON
        /// </summary>
        /// <exception cref="AppointmentManagement.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<AppointmentManagement.Client.Client.ApiResponse<Object>> GetAppointmentsWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            AppointmentManagement.Client.Client.RequestOptions localVarRequestOptions = new AppointmentManagement.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/xml"
            };

            var localVarContentType = AppointmentManagement.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = AppointmentManagement.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "APPOINTMENTApi.GetAppointments";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (appointmentmanagement_auth) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<Object>("/appointments", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetAppointments", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Replace a single appointment Replace a single appointment by Id
        /// </summary>
        /// <exception cref="AppointmentManagement.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appointmentID"></param>
        /// <param name="APPOINTMENT"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        public void ReplaceAppointment(Object appointmentID, APPOINTMENT APPOINTMENT, int operationIndex = 0)
        {
            ReplaceAppointmentWithHttpInfo(appointmentID, APPOINTMENT);
        }

        /// <summary>
        /// Replace a single appointment Replace a single appointment by Id
        /// </summary>
        /// <exception cref="AppointmentManagement.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appointmentID"></param>
        /// <param name="APPOINTMENT"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public AppointmentManagement.Client.Client.ApiResponse<Object> ReplaceAppointmentWithHttpInfo(Object appointmentID, APPOINTMENT APPOINTMENT, int operationIndex = 0)
        {
            // verify the required parameter 'appointmentID' is set
            if (appointmentID == null)
            {
                throw new AppointmentManagement.Client.Client.ApiException(400, "Missing required parameter 'appointmentID' when calling APPOINTMENTApi->ReplaceAppointment");
            }

            // verify the required parameter 'APPOINTMENT' is set
            if (APPOINTMENT == null)
            {
                throw new AppointmentManagement.Client.Client.ApiException(400, "Missing required parameter 'APPOINTMENT' when calling APPOINTMENTApi->ReplaceAppointment");
            }

            AppointmentManagement.Client.Client.RequestOptions localVarRequestOptions = new AppointmentManagement.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = AppointmentManagement.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = AppointmentManagement.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("AppointmentID", AppointmentManagement.Client.Client.ClientUtils.ParameterToString(appointmentID)); // path parameter
            localVarRequestOptions.Data = APPOINTMENT;

            localVarRequestOptions.Operation = "APPOINTMENTApi.ReplaceAppointment";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (appointmentmanagement_auth) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = this.Client.Put<Object>("/appointments/{AppointmentID}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ReplaceAppointment", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Replace a single appointment Replace a single appointment by Id
        /// </summary>
        /// <exception cref="AppointmentManagement.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appointmentID"></param>
        /// <param name="APPOINTMENT"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task ReplaceAppointmentAsync(Object appointmentID, APPOINTMENT APPOINTMENT, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            await ReplaceAppointmentWithHttpInfoAsync(appointmentID, APPOINTMENT, operationIndex, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Replace a single appointment Replace a single appointment by Id
        /// </summary>
        /// <exception cref="AppointmentManagement.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appointmentID"></param>
        /// <param name="APPOINTMENT"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<AppointmentManagement.Client.Client.ApiResponse<Object>> ReplaceAppointmentWithHttpInfoAsync(Object appointmentID, APPOINTMENT APPOINTMENT, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'appointmentID' is set
            if (appointmentID == null)
            {
                throw new AppointmentManagement.Client.Client.ApiException(400, "Missing required parameter 'appointmentID' when calling APPOINTMENTApi->ReplaceAppointment");
            }

            // verify the required parameter 'APPOINTMENT' is set
            if (APPOINTMENT == null)
            {
                throw new AppointmentManagement.Client.Client.ApiException(400, "Missing required parameter 'APPOINTMENT' when calling APPOINTMENTApi->ReplaceAppointment");
            }


            AppointmentManagement.Client.Client.RequestOptions localVarRequestOptions = new AppointmentManagement.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = AppointmentManagement.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = AppointmentManagement.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("AppointmentID", AppointmentManagement.Client.Client.ClientUtils.ParameterToString(appointmentID)); // path parameter
            localVarRequestOptions.Data = APPOINTMENT;

            localVarRequestOptions.Operation = "APPOINTMENTApi.ReplaceAppointment";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (appointmentmanagement_auth) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PutAsync<Object>("/appointments/{AppointmentID}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ReplaceAppointment", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
